package gestion;

import DB_Connect.Parameter;
import DB_Connect.ResultSetTableModel;
import DB_Connect.db_connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mediatech
 */
public class Produit extends javax.swing.JPanel {

    /**
     * Creates new form Produit
     */
    ResultSet rs;
    db_connection db;
    public Produit() {
        db = new db_connection(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        initComponents();
        table();
    }
    public void table() {
        String t[] = {"Code_produit","Nom_Produit","Fournisseur","remise","Prix","Stock","Stock_Minimum"};
        rs = db.querySelect(t, "produit");
        tbl_prod.setModel(new ResultSetTableModel(rs));
    }
     void actualiser() {
        txtid.setText("");
        txtNom.setText("");
        txtRem.setText("");
        txtfou.setText("");
        txtpri.setText("");
        txtsto.setText("");
        txtstoMin.setText("");
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_prod = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtRem = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtpri = new javax.swing.JTextField();
        txtsto = new javax.swing.JTextField();
        txtfou = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtstoMin = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        comrech = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtrech = new javax.swing.JTextField();
        head = new javax.swing.JLabel();

        setBackground(new java.awt.Color(85, 65, 118));

        tbl_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "code_produit", "Nom_Produit", "fournisseur", "remise", "prix", "stock ", "Stock Minimum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_prod.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_prod.setRowHeight(30);
        tbl_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_prodMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_prod);

        jPanel9.setBackground(new java.awt.Color(85, 65, 118));
        jPanel9.setPreferredSize(new java.awt.Dimension(850, 500));
        jPanel9.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Code produit   :");
        jPanel9.add(jLabel11);
        jLabel11.setBounds(10, 10, 110, 27);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fournisseur  :");
        jPanel9.add(jLabel12);
        jLabel12.setBounds(250, 20, 100, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nom Produit");
        jPanel9.add(jLabel13);
        jLabel13.setBounds(10, 60, 110, 27);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Remise   :");
        jPanel9.add(jLabel14);
        jLabel14.setBounds(10, 110, 110, 27);
        jPanel9.add(txtRem);
        txtRem.setBounds(120, 110, 100, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Prix   :");
        jPanel9.add(jLabel15);
        jLabel15.setBounds(260, 60, 100, 27);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Stock   :");
        jPanel9.add(jLabel16);
        jLabel16.setBounds(260, 110, 90, 27);

        txtid.setEditable(false);
        jPanel9.add(txtid);
        txtid.setBounds(120, 10, 100, 30);
        jPanel9.add(txtNom);
        txtNom.setBounds(120, 60, 100, 30);
        jPanel9.add(txtpri);
        txtpri.setBounds(360, 60, 100, 30);
        jPanel9.add(txtsto);
        txtsto.setBounds(360, 110, 100, 30);
        jPanel9.add(txtfou);
        txtfou.setBounds(360, 10, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Stock Minimum");
        jPanel9.add(jLabel1);
        jLabel1.setBounds(10, 160, 100, 30);
        jPanel9.add(txtstoMin);
        txtstoMin.setBounds(120, 160, 100, 30);

        jButton9.setBackground(new java.awt.Color(34, 167, 240));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Actualiser");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(242, 38, 19));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Supprimer");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(34, 167, 240));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Modifier");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(50, 194, 77));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Ajouter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(85, 65, 118));
        jPanel8.setLayout(null);

        jButton10.setBackground(new java.awt.Color(34, 167, 240));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Recherche ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton10);
        jButton10.setBounds(40, 190, 240, 40);

        comrech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Code_produit", "Nom_Produit", "fournisseur", "remise", "prix", "stock" }));
        jPanel8.add(comrech);
        comrech.setBounds(40, 70, 240, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Recherche par catégorie :");
        jPanel8.add(jLabel10);
        jLabel10.setBounds(40, 20, 250, 30);
        jPanel8.add(txtrech);
        txtrech.setBounds(40, 130, 240, 40);

        head.setBackground(new java.awt.Color(85, 65, 118));
        head.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 255));
        head.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_prodMouseClicked
        txtid.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 0)));
        txtNom.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 1)));
        txtfou.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 2)));
        txtRem.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 3)));
        txtpri.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 4)));
        txtsto.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 5)));
        txtstoMin.setText(String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 6)));
    }//GEN-LAST:event_tbl_prodMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        actualiser(); table();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String id = String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "est ce que tu es sure que tu veux suuprimer", "attention!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("produit", "Code_produit=" + id);
            actualiser();
            head.setText("Le produit a été suprimer");
            head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/img/error.png")));
            head.setBackground(new java.awt.Color(50,194,77));
        } else {
            return;
        }
        table();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (txtid.getText().equals("") || txtNom.getText().equals("") || txtRem.getText().equals("")
            || txtfou.getText().equals("") 
            || txtpri.getText().equals("") || txtsto.getText().equals("") || txtstoMin.getText().equals("")
        ) {
            head.setText("SVP entrer les informations complete");
            head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/img/error.png")));
            head.setBackground(new java.awt.Color(242,38,19));
        } else {
            head.setVisible(false);
            String[] colon = {"Nom_Produit","remise","fournisseur","prix","stock","Stock_Minimum"};
            String[] inf = {txtNom.getText(), txtRem.getText(),txtfou.getText()
                ,txtpri.getText(),txtsto.getText(),txtstoMin.getText()};
            String id = String.valueOf(tbl_prod.getValueAt(tbl_prod.getSelectedRow(), 0));
            System.out.println(db.queryUpdate("produit", colon, inf, "Code_produit='" + id + "'"));
            table();
            actualiser();
            head.setText("Le produit a été modifier");
            head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/img/error.png")));
            head.setBackground(new java.awt.Color(50,194,77));
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (txtNom.getText().equals("") || txtRem.getText().equals("")
            || txtfou.getText().equals("") 
            || txtpri.getText().equals("") || txtsto.getText().equals("") || txtstoMin.getText().equals("")
        ) {
            head.setText("SVP entrer les informations complete");
            head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/img/error.png")));
            head.setBackground(new java.awt.Color(242,38,19));
        } else {
            String[] colon = {"Nom_Produit","remise","fournisseur","prix","stock","Stock_Minimum"};
            String[] inf = {txtNom.getText(), txtRem.getText(),txtfou.getText()
                ,txtpri.getText(),txtsto.getText(),txtstoMin.getText()};
            System.out.println(db.queryInsert("produit", colon, inf));
            table();
            actualiser();
            head.setText("Le produit a été ajouter");
            head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/img/error.png")));
            head.setBackground(new java.awt.Color(50,194,77));
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (txtrech.getText().equals("")) {
            head.setText("SVP entrer quelque chose");
            head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/img/error.png")));
            head.setBackground(new java.awt.Color(242,38,19));
            
        } else {
            if (comrech.getSelectedItem().equals("Code_produit")) {
                rs = db.querySelectAll("produit", "Code_produit LIKE '%" + txtrech.getText() + "%' ");
                tbl_prod.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("Nom_Produit")) {
                rs = db.querySelectAll("produit", "Nom_Produit LIKE '%" + txtrech.getText() + "%' ");
                tbl_prod.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("remise")) {
                rs = db.querySelectAll("produit", "remise LIKE '%" + txtrech.getText() + "%' ");
                tbl_prod.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("fournisseur")) {
                rs = db.querySelectAll("produit", "fournisseur LIKE '%" + txtrech.getText() + "%' ");
                tbl_prod.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("prix")) {
                rs = db.querySelectAll("produit", "prix LIKE '%" + txtrech.getText() + "%' ");
                tbl_prod.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("stock")) {
                rs = db.querySelectAll("produit", "stock LIKE '%" + txtrech.getText() + "%' ");
                tbl_prod.setModel(new ResultSetTableModel(rs));

            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comrech;
    private javax.swing.JLabel head;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_prod;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtRem;
    private javax.swing.JTextField txtfou;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtpri;
    private javax.swing.JTextField txtrech;
    private javax.swing.JTextField txtsto;
    private javax.swing.JTextField txtstoMin;
    // End of variables declaration//GEN-END:variables
}
